name: ToongSaurusPlugin
version: 1.0.0
main: io.dogsbean.toong.Main
api-version: '1.21'
author: Dogsbean
description: 퉁퉁퉁 사후루스 야생 서버 전직 플러그인

commands:
  사후루스:
    description: 퉁퉁퉁 사후루스 메인 명령어
    usage: /사후루스 [정보|스킬|신전생성]
    aliases: [toongsaurus, 사후, ts]

permissions:
  toongsaurus.admin:
    description: 관리자 권한 (신전 생성)
    default: op
  toongsaurus.use:
    description: 일반 사용자 권한
    default: true